language: perl
sudo: false

perl:
  - "5.8"
  - "5.20"
install:
  - ( dzil authordeps --missing | cpanm --no-skip-satisfied )
  - ( dzil listdeps --author --missing | cpanm --no-skip-satisfied )
  - make .cpanfile_dependencies
script:
  - "echo -e 'Feature: foo\n  Scenario: bar\n    Given zap' > f.feature && perl bin/gherkin-generate-pickles f.feature"
